server:
  port: 1314
  servlet:
    context-path: /kafkaStudy

spring:
  kafka:
    bootstrap-servers: 192.168.16.129:9092,192.168.16.129:9093,192.168.16.129:9094
    producer:
      retries: 0
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          ms: 0
        partitioner:
          class: com.aze.kafkastudyspringboot.kafka.CustomizePartitioner
    consumer:
      properties:
        group:
          id: defaultConsumerGroup
        session:
          timeout:
            ms: 120000
        request:
          timeout:
            ms:180000
      enable-auto-commit: true
      auto:
        commit:
          interval:
            ms: 1000
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      missing-topics-fatal: false
